
version: '3'
services:
    gateway:
        build:
          context: ./gateway
          dockerfile: Dockerfile
        ports:
            - '80:80'
        environment:
            COMMENTS_SERVICE: comments:50051
        volumes:
            - "./gateway/src:/usr/src/app/src/:cached"
        networks:
            lesson_vpn:
                aliases:
                    - gateway
    comments:
        build:
          context: ./comments
          dockerfile: Dockerfile
        environment:
            BIND_LOCATION: comments:50051
        volumes:
            - "./comments/src:/usr/src/app/src/:cached"
        networks:
            lesson_vpn:
                aliases:
                    - comments
networks:
    lesson_vpn: