
version: '3.7'
services:
    gateway:
        image: microservices_gateway
        build:
          context: ./gateway
          dockerfile: Dockerfile
        ports:
            - '80:80'
        environment:
            COMMENTS_SERVICE: comments-service:50051
            AMPQ_SERVICE: amqp://ampq:5672
            POSTS_SERVICE: http://posts-service/posts/:post_uuid
        volumes:
            - "./gateway/src:/usr/src/app/src/:cached"
        networks:
            lesson_vpn:
                aliases:
                    - gateway-service
    comments:
        image: microservices_comments
        build:
          context: ./comments
          dockerfile: Dockerfile
        environment:
            MONGO_URL: mongodb://comments-db:27017
            BIND_LOCATION: 0.0.0.0:50051
        deploy:
            mode: replicated
            replicas: 2
            endpoint_mode: dnsrr
        volumes:
            - "./comments/src:/usr/src/app/src/:cached"
        networks:
            comments_vpn:
            lesson_vpn:
                aliases:
                    - comments-service
    fetch:
        image: microservices_fetch
        build:
          context: ./fetch
          dockerfile: Dockerfile
        environment:
            AMPQ_SERVICE: amqp://ampq:5672
        volumes:
            - "./fetch/src:/usr/src/app/src/:cached"
        networks:
            lesson_vpn:
                aliases:
                    - fetch-service
    posts:
        image: microservices_posts
        build:
          context: ./posts
          dockerfile: Dockerfile
        environment:
            PSQL_URL: postgresql://postgres:@posts-db:5432/posts
        volumes:
            - "./posts/src:/usr/src/app/src/:cached"
        networks:
            posts_vpn:
            lesson_vpn:
                aliases:
                    - posts-service
    comments-db:
        image: mongo:4.2.0
        networks:
            comments_vpn:
                aliases:
                    - comments-db
    posts-db:
        image: microservices_posts-db
        build:
          context: ./posts-db
          dockerfile: Dockerfile
        networks:
            posts_vpn:
                aliases:
                    - posts-db
    ampq:
        image: rabbitmq:3.7.1
        networks:
            lesson_vpn:
                aliases:
                    - ampq
networks:
    lesson_vpn:
    comments_vpn:
    posts_vpn:
        