
version: '3.7'
services:
    gateway:
        image: microservices_gateway
        build:
          context: ./gateway
          dockerfile: Dockerfile
        ports:
            - '80:80'
        environment:
            COMMENTS_SERVICE: comments-service:50051
        volumes:
            - "./gateway/src:/usr/src/app/src/:cached"
        networks:
            lesson_vpn:
                aliases:
                    - gateway
    comments:
        image: microservices_comments
        build:
          context: ./comments
          dockerfile: Dockerfile
        environment:
            MONGO_URL: mongodb://comments-db:27017
            BIND_LOCATION: 0.0.0.0:50051
        deploy:
            mode: replicated
            replicas: 2
            endpoint_mode: dnsrr
        volumes:
            - "./comments/src:/usr/src/app/src/:cached"
        networks:
            comments_vpn:
            lesson_vpn:
                aliases:
                    - comments-service
    comments-db:
        image: mongo:4.2.0
        networks:
            comments_vpn:
                aliases:
                    - comments-db

networks:
    lesson_vpn:
    comments_vpn:
        